apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: flagger-appmesh-gateway
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flagger-appmesh-gateway
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 99
