apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- account.yaml
- deployment.yaml
- service.yaml
- hpa.yaml
- rbac.yaml
configMapGenerator:
  - name: flagger-appmesh-gateway
    files:
      - envoy.yaml
