apiVersion: v1
kind: Service
metadata:
  name: flagger-appmesh-gateway
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
