name: build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Go fmt
        uses: stefanprodan/kube-tools@v1
        with:
          command: make go-fmt
      - name: Go test
        uses: stefanprodan/kube-tools@v1
        with:
          command: make test
      - name: Validate kustomization
        uses: stefanprodan/kube-tools@v1
        with:
          command: |
            echo "build gateway"
            kustomize build ./kustomize/nlb | kubeval --strict --ignore-missing-schemas
            kustomize build ./kustomize/nodeport | kubeval --strict --ignore-missing-schemas
            echo "build test"
            kustomize build ./kustomize/test | kubeval --strict --ignore-missing-schemas
  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v1
      - name: Build container
        run: make build-container
